CREATE TABLE IF NOT EXISTS CONTAS (
  ID                 INTEGER          NOT NULL    AUTO_INCREMENT,
  DESCRICAO          VARCHAR(50)  NOT NULL,
  VENCIMENTO         DATE         NOT NULL,
  PARCELAS           VARCHAR(10),
  ID_CARTAO          INTEGER,
  TIPO_PAGAMENTO     VARCHAR(1),
  PRIMARY KEY PK_CONTAS (ID)
);