CREATE TABLE IF NOT EXISTS CONTAS (
  ID                 INTEGER          NOT NULL    AUTO_INCREMENT,
  DESCRICAO          VARCHAR(50)  NOT NULL,
  VENCIMENTO         DATE,
  PARCELAS           VARCHAR(10),
  ID_CARTAO          INTEGER,
  TIPO_PAGAMENTO     VARCHAR(1),
  OBSERVACAO         VARCHAR(60),
  DT_CONTA           DATE,
  VALOR              DECIMAL(15,2),
  PRIMARY KEY PK_CONTAS (ID)
);

ALTER TABLE CONTAS ADD CONSTRAINT FK_CARTAO FOREIGN KEY(ID_CARTAO) REFERENCES CARTAO (ID);