CREATE TABLE IF NOT EXISTS CREDENCIADORA(
  ID                 INT          NOT NULL    AUTO_INCREMENT,
  CREDENCIADORA      VARCHAR(150)  NOT NULL,
  CNPJ               VARCHAR(14)  NOT NULL,
  PRIMARY KEY PK_CREDENCIADORA (ID)
);

ALTER TABLE CARTAO ADD CONSTRAINT FK_CREDENCIADORA FOREIGN KEY(ID_CREDENCIADORA) REFERENCES CREDENCIADORA (ID);