CREATE TABLE IF NOT EXISTS CREDENCIADORA(
  ID                 INT          NOT NULL    AUTO_INCREMENT,
  CREDENCIADORA      VARCHAR(50)  NOT NULL,
  CNPJ               VARCHAR(50)  NOT NULL,
  PRIMARY KEY PK_CREDENCIADORA (ID)
);
