CREATE TABLE IF NOT EXISTS USUARIO(
  ID                 BIGINT       NOT NULL    AUTO_INCREMENT,
  NOME               VARCHAR(50)  NOT NULL,
  USUARIO            VARCHAR(50)  NOT NULL,
  SENHA              VARCHAR(50)  NOT NULL,
  PRIMARY KEY PK_USUARIO (ID)
);
