CREATE TABLE IF NOT EXISTS BANDEIRA(
  ID                 INTEGER       NOT NULL    AUTO_INCREMENT,
  DESCRICAO          VARCHAR(100)  NOT NULL,
  PRIMARY KEY PK_BANDEIRA (ID)
);

ALTER TABLE CARTAO ADD CONSTRAINT FK_BANDEIRA FOREIGN KEY(ID_BANDEIRA) REFERENCES BANDEIRA(ID);