INSERT INTO BANDEIRA (DESCRICAO) VALUES ('Visa');
INSERT INTO BANDEIRA (DESCRICAO) VALUES ('MasterCard');
INSERT INTO BANDEIRA (DESCRICAO) VALUES ('Elo');
INSERT INTO BANDEIRA (DESCRICAO) VALUES ('American Express');
INSERT INTO BANDEIRA (DESCRICAO) VALUES ('CooperCard');
INSERT INTO BANDEIRA (DESCRICAO) VALUES ('Dinner');